set CPU		idle
set CPU		256K
#set CPU	1024K
#set CPU	ONESEG
#set CPU	TWOSEG
#set CPU	ITS
#set CPU	BBN
#set CPU	WAITS
#set CPU	NOWAITS
#set CPU	MPX
#set CPU	NOMPX

set CTY		7B

set PTP		disable
set PTR		enable
set LPT		disable
set CR		disable
set CP		disable
set DCT		disable
set MTA		disable
set MTC		disable
set DPA		disable
set DPB		disable
set FSA		disable
set RPA		disable
set RPB		disable
set RPC		disable
set RPD		disable
set DSK		disable
set FHA		disable
set PMP		disable
set DT		disable
set DTC		disable
set DC		disable
set DCS		disable
set DK		disable
set PD		disable
set PCLK 	disable
set DPY		disable
set WCNSLS	disable
set OCNSLS	disable
set III		disable
set TUA		disable
set TV		disable
set DD		disable
set VDS		disable
set IMP		disable
set CH		disable
set IMX		disable
set STK		disable
set TK		disable
set MTY		disable
set TEN11	disable
set AUXCPU	disable
set DKB		disable
set DPK		disable
set AI		disable
set DDC		disable
