set CPU		idle
set CPU		256K
#set CPU	4096K
#set CPU	DF10
#set CPU	DF10C

set CTY		7B

set PTP		disable
set PTR		enable
set LPT		disable
set CR		disable
set CP		disable
set MTA		disable
set DPA		disable
set DPB		disable
set FSA		disable
set RPA		disable
set RPB		disable
set RPC		disable
set RPD		disable
set FHA		disable
set TUA		disable
set DT		disable
set DC		disable
set DK		disable
set DPY		disable
set WCNSLS	disable
set OCNSLS	disable
set IMP		disable
set DDC		disable
