set CPU		idle
set CPU		256K
#set CPU	1024K
#set CPU	ITS

set CTY		7B

set TUA		disable
set IMP		disable
set LP20	disable
set RPA		disable
set CH		disable
set DZ		disable
set TIM		disable
set KDP		disable
set DUP		disable
