set CPU		idle
set CPU		256K
#set CPU	4096K
#set CPU	KL10A
#set CPU	KL10B
#set CPU	ITS
#set CPU	DF10
#set CPU	DF10C

#set CTY	7B

set PTP		disable
set PTR		enable
set LPT		disable
set LP20	disable
set CR		disable
set CP		disable
set MTA		disable
set DPA		disable
set DPB		disable
set FSA		disable
set RPA		disable
set RPB		disable
set RPC		disable
set RPD		disable
set DT		disable
set DC		disable
set PD		disable
set TUA		disable
set IMP		disable
set CH		disable
set TTY		disable
