set CPU		idle
set CPU		256K

set CTY		7B

set PTP		disable
set PTR		enable
set CR		disable
set CP		disable
set DCT		disable
set DTC		disable
set MTC		disable
set MTC		disable
set DSK		disable
set DTC		disable
set DCS		disable
set DPY		disable
set WCNSLS	disable
set OCNSLS	disable
set SLAVE	disable
set GE		disable
#set GTYO	disable
